# Generated by Django 2.0.6 on 2020-05-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('img_url', models.ImageField(upload_to='carousel')),
            ],
            options={
                'db_table': 'carousel',
            },
        ),
    ]
